
development:
  adapter: postgresql
  database: tv_results_dev
  pool: 5
  username: postgres
  password:
  host: localhost 


test:
  adapter: postgresql
  database: tv_results_test
  pool: 5
  username: postgres
  password:
  host: localhost 
